import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GetForSsrsDocument, GetForSsrsQuery, useGetArticlesQuery} from '../generated/graphql';
import {graphqlClient} from "../apollo/graphqlClient";

const WithCodeGen: NextPage<{ssrData: any}> = ({ssrData}) => {
  // Client Side Fetch
  const { data } = useGetArticlesQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>Client Side Fetch</p>
        {data?.getArticles?.map(a => <p>{a?.id}: {a?.title}</p>)}
      </div>
      <div>
        <p>Server Side Fetch</p>
        {ssrData.map((data: any) => <p>
          {data.id}: {data.content}
        </p>)}
      </div>
    </div>
  )
}

export default WithCodeGen

export async function getServerSideProps() {
  const { data } = await graphqlClient.query<GetForSsrsQuery>({query: GetForSsrsDocument});
  return {
    props: {
      ssrData: data.getForSsrs,
    },
  }
}